# -*- coding: utf-8 -*-
"""
Created on Sun Oct  2 19:31:42 2016

@author: user
"""

counties = ["Avon",
            "Manchester",
            "Bedfordshire",
            "Berkshire",
            "Buckinghamshire",
            "Cambridgeshire",
            "Cheshire",
            "Cleveland",
            "Cornwall",
            "Cumbria",
            "Derbyshire",
            "Devon",
            "Dorset",
            "Durham",
            "East Sussex",
            "Essex",
            "Gloucestershire",
            "Hampshire",
            "Herefordshire",
            "Hertfordshire",
            "Isle of Wight",
            "Kent",
    		"Lancashire",
    		"Leicestershire",
    		"Lincolnshire",
    		"London",
    		"Merseyside",
    		"Middlesex",
    		"Norfolk",
    		"Northamptonshire",
    		"Northumberland",
    		"North Humberside",
    		"North Yorkshire",
    		"Nottinghamshire",
    		"Oxfordshire",
    		"Rutland",
    		"Shropshire",
    		"Somerset",
    		"South Humberside",
    		"South Yorkshire",
    		"Staffordshire",
    		"Suffolk",
    		"Surrey",
    		"Tyne and Wear",
    		"Warwickshire",
    		"West Midlands",
    		"West Sussex",
    		"West Yorkshire",
    		"Wiltshire",
    		"Worcestershire",
    		"Clwyd",
    		"Dyfed",
    		"Gwent",
    		"Gwynedd",
    		"Mid Glamorgan",
    		"Powys",
    		"South Glamorgan",
    		"West Glamorgan",
    		"Aberdeenshire",
    		"Angus",
    		"Argyll",
    		"Ayrshire",
    		"Banffshire",
    		"Berwickshire",
    		"Bute",
    		"Caithness",
    		"Clackmannanshire",
    		"Dumfriesshire",
    		"Dunbartonshire",
    		"East Lothian",
    		"Fife",
    		"Inverness-shire",
    		"Kincardineshire",
    		"Kinross-shire",
    		"Kirkcudbrightshire",
    		"Lanarkshire",
    		"Midlothian",
    		"Moray",
    		"Nairnshire",
    		"Orkney",
    		"Peeblesshire",
    		"Perthshire",
    		"Renfrewshire",
    		"Ross-shire",
    		"Roxburghshire",
    		"Selkirkshire",
    		"Shetland",
    		"Stirlingshire",
    		"Sutherland",
    		"West Lothian",
    		"Wigtownshire",
    		"Antrim",
    		"Armagh",
    		"Down",
    		"Fermanagh",
    		"Londonderry",
    		"Tyrone"]