# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('idaddress', models.AutoField(db_column='idAddress', primary_key=True, serialize=False)),
                ('postcode', models.CharField(max_length=10)),
                ('housenumber', models.CharField(blank=True, db_column='houseNumber', max_length=200, null=True)),
                ('county', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('idcustomer', models.AutoField(db_column='idCustomer', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=200)),
                ('lastname', models.CharField(db_column='lastName', max_length=200)),
                ('blacklist', models.IntegerField()),
                ('emailaddress', models.CharField(blank=True, db_column='eMailAddress', max_length=200, null=True)),
                ('contactnumber', models.CharField(blank=True, db_column='contactNumber', max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=45, null=True)),
                ('dob', models.CharField(blank=True, max_length=45, null=True)),
                ('maritalstatus', models.CharField(blank=True, db_column='maritalStatus', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idemployee', models.AutoField(db_column='idEmployee', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=45, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=45, null=True)),
                ('department', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('idpayment', models.AutoField(db_column='idPayment', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('cardnumber', models.CharField(blank=True, db_column='cardNumber', max_length=45, null=True)),
                ('expirydate', models.DateField(blank=True, db_column='expiryDate', null=True)),
            ],
            options={
                'db_table': 'Payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idproduct', models.AutoField(db_column='idProduct', primary_key=True, serialize=False)),
                ('productname', models.CharField(blank=True, db_column='productName', max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('buyprice', models.FloatField(blank=True, db_column='buyPrice', null=True)),
                ('saleprice', models.FloatField(blank=True, db_column='salePrice', null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('idpurchase', models.AutoField(db_column='idPurchase', primary_key=True, serialize=False)),
                ('purchasestatus', models.CharField(blank=True, db_column='purchaseStatus', max_length=200, null=True)),
                ('createdate', models.DateField(blank=True, db_column='createDate', null=True)),
                ('gdzdate', models.DateField(blank=True, db_column='GDZDate', null=True)),
                ('dispatcheddate', models.DateField(blank=True, db_column='dispatchedDate', null=True)),
                ('delivereddate', models.DateField(blank=True, db_column='deliveredDate', null=True)),
                ('cancelleddate', models.DateField(blank=True, db_column='cancelledDate', null=True)),
                ('returneddate', models.DateField(blank=True, db_column='returnedDate', null=True)),
            ],
            options={
                'db_table': 'Purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchaselines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PurchaseLines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('idsupplier', models.AutoField(db_column='idSupplier', primary_key=True, serialize=False)),
                ('contactnumber', models.CharField(blank=True, db_column='contactNumber', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplierorder',
            fields=[
                ('idsupplierorder', models.IntegerField(db_column='idSupplierOrder', primary_key=True, serialize=False)),
                ('createdate', models.CharField(blank=True, db_column='createDate', max_length=45, null=True)),
                ('deliverydate', models.CharField(blank=True, db_column='deliveryDate', max_length=45, null=True)),
            ],
            options={
                'db_table': 'SupplierOrder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplierorderlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'SupplierOrderLines',
                'managed': False,
            },
        ),
    ]
